### ISSUE TITLE
Ajouter Lettre de Cécile T. Chassé concernant un lègue de quatre dollars

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-MSS-19#17]
https://traces6.paris.inria.fr/document/1588/images/

@dtsoline, comme la transcription est prête,  n'hésitez pas à faire la Pull Request correspondante

**Comment by dtsoline** [comment]
C'est fait, merci @alix-tz.

**Comment by alix-tz** [comment]
résolu avec #19 ! :)
