### ISSUE TITLE
Difficultés transcriptions Notes manuscrites Zola

### ISSUE THREAD

**Issue by rayondemiel** [HTR-United/CREMMA-MSS-19#4]
Bonjour à tous,

J'ai un certains nombres de mots que je n'arrive pas à transcrite:

![1-1](https://user-images.githubusercontent.com/88341216/156176684-758c2831-04d9-4d0f-80f7-79e8c1a41263.png)
Phrase : Les fours à Col[[ie]] de la Cie, près de la

---

![2-1](https://user-images.githubusercontent.com/88341216/156176809-d486f061-09e7-4afb-a4bb-165d39157b4a.png)
Phrase: les dents blanches. Quand à la [[rient]] des

![2-2](https://user-images.githubusercontent.com/88341216/156176892-e2a9e7b5-733a-4e49-8313-e4e132c4bc05.png)
Phrase: uien[[te]] au fond de cette tranche beau

---
![3-1](https://user-images.githubusercontent.com/88341216/156177015-c3ac15d1-b22d-43f0-965e-bbf2c933b6f8.png)
Phrase: vie à Marchiennes est à *******

![3-2](https://user-images.githubusercontent.com/88341216/156177090-967b7a81-b1e1-428f-84b1-ba332bd9ff68.png)
Phrase (suite): [[marchèe]]. 

---
![4-1](https://user-images.githubusercontent.com/88341216/156177229-72715293-a304-4537-a89f-1e897a4f4ede.png)
Phrase: le perrit[[aire]] (179)

---

![5-1](https://user-images.githubusercontent.com/88341216/156177345-c2b1876a-04d9-47b5-97af-118118603b96.png)
Phrase: latrai[[xx]] plus tard

![5-2](https://user-images.githubusercontent.com/88341216/156177503-4d5fbab2-2364-4717-a0b7-ddb2e823d520.png)
Phrase: Le caractère ahi mineur ! Bonhomme et qu'- peri[[t]]ct[[iaire]]

![5-3](https://user-images.githubusercontent.com/88341216/156177658-74399c81-fe22-4cec-97d7-8a9af3c34a9e.png)
Phrase: La *** [[future]] très commune

![5-4](https://user-images.githubusercontent.com/88341216/156177830-2c2135b4-6668-48af-ae0a-17b3deaf1701.png)

Phrase: La houille grasse plus de gaz et de [[atttivie]]

---

Merci d'avance pour votre aide.

**Comment by PonteIneptique** [comment]
Pensez à mettre des liens voire des images plus grandes :)

![image](https://user-images.githubusercontent.com/1929830/156179165-208b5640-aa7f-4f45-98fc-57b7175307c2.png)
Quand ils rient (trouvé sur Cairn)

**Comment by PonteIneptique** [comment]
> [](https://user-images.githubusercontent.com/88341216/156176684-758c2831-04d9-4d0f-80f7-79e8c1a41263.png)1-1
Phrase : Les fours à Col[[ie]] de la Cie, près de la
Les fours à Coke

**Comment by PonteIneptique** [comment]
[](https://user-images.githubusercontent.com/88341216/156177015-c3ac15d1-b22d-43f0-965e-bbf2c933b6f8.png)[](https://user-images.githubusercontent.com/88341216/156177090-967b7a81-b1e1-428f-84b1-ba332bd9ff68.png)3-1
Phrase: vie à Marchiennes est à *******

3-2
Phrase (suite): [[marchèe]].

La vie à Marchiennes est à meilleur 
marchè

**Comment by alix-tz** [comment]
![image](https://user-images.githubusercontent.com/33317799/156185823-982526f3-f0e5-41a2-b618-494581dd1477.png)
![image](https://user-images.githubusercontent.com/33317799/156185858-ea6f5994-202d-4ea4-8985-ec98f5f1d3a1.png)

Sans franche certitude, je lis : 
formes s'agit**a**nt dans la nuit fu-
meuse au fond de cette tranche beau  


![image](https://user-images.githubusercontent.com/33317799/156186282-364b4dbb-d992-4236-904c-10576b004fe1.png)

Ici je lis plutôt "la veine. L'ouvrier se me**t** sur **le flanc**,"

![image](https://user-images.githubusercontent.com/33317799/156207187-45778af1-b215-4827-aede-6c568e7fde2d.png)
Ici je lis plutôt "(169) **S**odo**m**e En Belgique (169)"

**Comment by alix-tz** [comment]
![image](https://user-images.githubusercontent.com/33317799/156210247-aa4986e1-a1e8-4571-a0b4-98f10b3501c9.png)

Je lis "Le **pénitent** (179)", ce qui correspond au registre religieux utilisé par Zola ici.

**Comment by alix-tz** [comment]
![image](https://user-images.githubusercontent.com/33317799/156211588-c1f6b928-be05-4c16-9906-ba5cd5f9083f.png)


Peut-être "Latrons", mais il faudrait presque voir la phrase de la page précédente. 


![image](https://user-images.githubusercontent.com/33317799/156211701-b833b5f7-2933-4445-b2d3-a028fa8f879b.png)
![image](https://user-images.githubusercontent.com/33317799/156211760-769656cf-9381-4853-a796-8cef56960002.png)

"Le caractère **du** mineur ! Bonho**mie** et **su** -"
"perstition" (celui-là était vraiment dur!!)

**Comment by alix-tz** [comment]
![image](https://user-images.githubusercontent.com/33317799/156214719-002bf6e6-b968-4ecf-8b12-31725dcb203c.png)

Je pense "scrofulose" (https://www.dictionnairedesfrancophones.org/form/scrofulose)

**Comment by rayondemiel** [comment]
Je vous remercie pour vos réponses. 
Pour le dernier, il n'y a aucune concordance de ce mot au sein de l'édition de wikisource avec le mot gaz. J'ai pensé à "asthme" dont le s a été corrigé a posteriori. La ligne précédente évoque l'asthme de Bonnemort

**Comment by alix-tz** [comment]
Effectivement ça colle bien!

**Comment by alix-tz** [comment]
je ferme car ces difficultés de transcription sont résolues.
